import Head from 'next/head'

import Botao from '../components/Botao'
import Formulario from '../components/Formulario'

import Layout from '../components/Layout'
import Tabela from '../components/Tabela'
import useClientes from '../hooks/useClientes'

export default function Home() {
  const { isTabela, cliente, clientes,
    exibirTable, clienteExcluido,
    clienteSelecionado, novoCliente,
    salvarCliente } = useClientes()

  return (
    <div className={`
      flex h-screen justify-center items-center
      bg-gradient-to-r from-purple-500  to-blue-600
    `}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout titulo="Cadastro simples">
        {isTabela ?
          (
            <>
              <div className={`flex justify-end`}>
                <Botao
                  cor="green"
                  className={`mb-2`}
                  onClick={novoCliente}
                >
                  Novo Cliente
                </Botao>
              </div>
              <Tabela
                clientes={clientes}
                clienteSelecionado={clienteSelecionado}
                clienteExcluido={clienteExcluido}
              />
            </>
          ) : (
            <Formulario
              cliente={cliente}
              clienteSalvo={salvarCliente}
              cancelado={exibirTable}
            />
          )}
      </Layout>
    </div>
  )
}
