import Head from 'next/head'
import Image from 'next/image'
import 'tailwindcss/tailwind.css'

export default function Home() {
  return (
    <div className={`
      flex h-screen justify-center items-center
      bg-gradient-to-r from-purple-500 via-yellow-500 to-blue-600
    `}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <span className={`text-4xl`}>
        Home
      </span>
    </div>
  )
}
