import Head from 'next/head'
import Layout from '../components/template/Layout'

export default function Ajustes() {
  return (
    <Layout
      title="Ajustes"
      subtitle="Aqui você irá gerenciar as suas ajustes">
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      conteudo!!
    </Layout>
  )
}
