import Head from 'next/head'
import Layout from '../components/template/Layout'

export default function Notificacoes() {
  return (
    <Layout
      title="Perfil"
      subtitle="Administre suas informaçoes.">
      <Head>
        <title>Admin App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h3>Perfil</h3>
    </Layout>
  )
}
